import { Platform } from "react-native";

// HelloHacks Figma: home 1:2, Schedule 1:1192, notes 1:1462.
export const palette = {
  ink: "#3F414E",
  muted: "#74798D",
  paper: "#FFFFFF",
  surface: "#FFFFFF",
  line: "#EBEBF2",
  coral: "#C85A6A",
  coralDark: "#A03C4C",
  coralPale: "#FBECEF",
  blue: "#626C99",
  bluePale: "#F0F1F8",
  lavender: "#BFC6DE",
  green: "#376C51",
  greenPale: "#E8F2EB",
  amber: "#8A6228",
  amberPale: "#F8F0E1",
  danger: "#A53D3D",
  dangerPale: "#F8EAEA",
  peach: "#F1DDCF",
  rose: "#E77989",
};
export const fontFamily = Platform.select({
  ios: "Helvetica Neue",
  web: "Helvetica Neue, Helvetica, Arial, sans-serif",
  default: "sans-serif",
});
export const artwork = {
  brain: require("../../assets/figma/brain.png"),
  calendar: require("../../assets/figma/calendar.png"),
  sunrise: require("../../assets/figma/sunrise.png"),
  morning: require("../../assets/figma/morning.png"),
  games: require("../../assets/figma/games.png"),
  timezone: require("../../assets/figma/timezone.png"),
  coast: require("../../assets/figma/coast.png"),
  garden: require("../../assets/figma/garden.png"),
  all: require("../../assets/figma/all-0.svg"),
  allTop: require("../../assets/figma/all-1.svg"),
  allBottom: require("../../assets/figma/all-2.svg"),
  allLeft: require("../../assets/figma/all-3.svg"),
  movie: require("../../assets/figma/movie.svg"),
  game: require("../../assets/figma/game.svg"),
  meal: require("../../assets/figma/recipe.svg"),
  home: require("../../assets/figma/home.svg"),
  homeActive: require("../../assets/figma/homeActive.svg"),
  checkin: require("../../assets/figma/checkin.svg"),
  checkinActive: require("../../assets/figma/checkinActive.svg"),
  ideas: require("../../assets/figma/ideas.svg"),
  ideasActive: require("../../assets/figma/ideasActive.svg"),
  upcoming: require("../../assets/figma/upcoming.svg"),
  upcomingActive: require("../../assets/figma/upcomingActive.svg"),
  account: require("../../assets/figma/account.svg"),
  accountActive: require("../../assets/figma/accountActive.svg"),
  promptHeart: require("../../assets/figma/promptHeart.svg"),
};
